### ISSUE TITLE
Documentar cómo ejecutar el módulo en el readme

### ISSUE THREAD

**Issue by joaquinceballos** [Arquisoft/Agents_e1a#1]
Una vez tengamos  claro cómo realizar la petición con los nuevos parámetros.

**Comment by joaquinceballos** [comment]
Las peticiones funcionan bien (aparentemente, desde JUnit no hay problemas), pero aún queda pendiente documentar bien cómo se hace.

**Comment by FernandoDelBarrio** [comment]
entre lo que hay en el Readme y la wiki podriamos dar estos por zanjado no?

**Comment by paula-clares** [comment]
ya está listo
