### ISSUE TITLE
Cambios en la logica

### ISSUE THREAD

**Issue by FernandoDelBarrio** [Arquisoft/Agents_e1a#2]
Cambios en los que estoy trabajando:
- Quito campos de Agent fecha de nacimiento , apellidos , nacionalidad y direccion
- Añado los campos coordenadas y tipo
- A la hora de hacer la peticion añado el campo tipo de usuario
- A la hora de realizar la respuesta se añade localizacion y tipo de usuario (para el numero de tipo de usuario necesitamos el fichero CSV )
- Adaptar pruebas tras estos cambios

**Comment by joaquinceballos** [comment]
Algunos de esos cambios ya estaban en la rama joaquin_inconsistente. Primeros fallos de comuniación detectados ;).

Mañana a las 14:00 hemos quedado Fernando y yo para una reunión rápida y poner en común los cambios.

**Comment by joaquinceballos** [comment]
Todos los cambios en la misma rama. Módulo 2 funcionando.
