### ISSUE TITLE
Warning al pasar las pruebas con mvn test

### ISSUE THREAD

**Issue by joaquinceballos** [Arquisoft/Agents_e1a#4]
Al correr las pruebas con Maven sale este warning que no aparecía en eclipse.

![image](https://user-images.githubusercontent.com/35779468/36065927-9703f62a-0ea1-11e8-8d43-9aaae1e918f9.png)

**Comment by FernandoDelBarrio** [comment]
La solucion seria poner esta dependencia en el pom.xml
![image](https://user-images.githubusercontent.com/35732615/36066325-ea97d882-0ea7-11e8-94e6-dca9c2416fb1.png)
